using Microsoft.AspNetCore.Mvc;
using ArchiveAPI.Services;
using System.ComponentModel.DataAnnotations;

namespace ArchiveAPI.Controllers;

/// <summary>
/// Controller for AI analysis operations
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class AnalysisController : ControllerBase
{
    private readonly IGeminiService _geminiService;
    private readonly ILogger<AnalysisController> _logger;

    public AnalysisController(IGeminiService geminiService, ILogger<AnalysisController> logger)
    {
        _geminiService = geminiService;
        _logger = logger;
    }

    /// <summary>
    /// Analyze an image using Gemini AI
    /// </summary>
    /// <remarks>
    /// Sends an image to Google's Gemini AI model for analysis.
    /// The image must be provided as a Base64 encoded string.
    /// You can optionally provide a custom prompt (default: "Describe this image in detail").
    /// </remarks>
    /// <param name="request">The image analysis request</param>
    /// <returns>The text description/analysis of the image</returns>
    /// <response code="200">Analysis successful</response>
    /// <response code="400">Invalid request (missing image)</response>
    /// <response code="500">Analysis failed</response>
    [HttpPost("image")]
    [ProducesResponseType(typeof(ImageAnalysisResponse), 200)]
    public async Task<IActionResult> AnalyzeImage([FromBody] ImageAnalysisRequest request)
    {
        if (request == null || string.IsNullOrWhiteSpace(request.Base64Image))
        {
            return BadRequest(new { error = "Image data is required" });
        }

        try
        {
            var result = await _geminiService.AnalyzeImageAsync(
                request.Base64Image, 
                request.MimeType ?? "image/jpeg", 
                request.Prompt ?? "Describe this image in detail."
            );
            
            return Ok(new ImageAnalysisResponse { Result = result });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error analyzing image");
            return StatusCode(500, new { error = "Internal server error during analysis" });
        }
    }
}

/// <summary>
/// Request model for image analysis
/// </summary>
public class ImageAnalysisRequest
{
    /// <summary>
    /// Base64 encoded image data (with or without data URI prefix)
    /// </summary>
    [Required]
    public string Base64Image { get; set; } = string.Empty;
    
    /// <summary>
    /// MIME type of the image (e.g., "image/jpeg", "image/png"). Default: "image/jpeg"
    /// </summary>
    public string? MimeType { get; set; } = "image/jpeg";
    
    /// <summary>
    /// Custom prompt for the AI. Default: "Describe this image in detail."
    /// </summary>
    public string? Prompt { get; set; }
}

/// <summary>
/// Response model for image analysis
/// </summary>
public class ImageAnalysisResponse
{
    /// <summary>
    /// The text result/description generated by the AI
    /// </summary>
    public string Result { get; set; } = string.Empty;
}

